swagger: '2.0'
info:
  description: >-
    This is the api gateway for the OpenBrisk serverless functions framework.
    You can find out more about OpenBrisk at [http://openbrisk.org](http://openbrisk.org).
  version: 1.0.0
  title: OpenBrisk API Gateway
  contact:
    email: info@openbrisk.org
  license:
    name: MIT
basePath: /gateway/v1
schemes:
  - http
paths:
  '/functions/{namespaceName}/{functionName}':
    post:
      summary: Invoke a deployed function.
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: namespaceName
          description: The namespace the function is located in.
          required: true
          type: string
        - in: path
          name: functionName
          description: The name of the function to invoke.
          required: true
          type: string
        - in: body
          name: body
          description: >-
            The call mode of the function and the optional data passed to the 
            function.
          required: true
          schema:
            $ref: '#/definitions/FunctionInvocationDescriptor'                 
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '404':
          description: Function Not Found
        '500':
          description: Internal Function Error
definitions:          
  FunctionInvocationDescriptor:
    type: object
    required:
      - async
    properties:
      async:
        type: boolean
        description: (Optional) The async call mode of the function invocation.
        default: false
      data:
        type: string
        description: (Optional) The data passed to the function.
        default: ''
externalDocs:
  description: OpenBrisk documentation available on GitHub.
  url: https://github.com/openbrisk/brisk